In [1]:
import pandas as pd
import os

In [2]:
# Uncomment for installation of openpyxl if not already installed
#pip install openpyxl

# **Love & Surprise**

## LoSu 1 ([Kaggle link](https://www.kaggle.com/datasets/praveengovi/emotions-dataset-for-nlp))

In [3]:
df1 = pd.read_csv("../data/raw/extra_dataset_Praveen.csv")
df1.head()

                                                text    label
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df1 = df1[df1['label'].isin(['love', 'surprise'])]
df1.head()

                                                 text     label
3   i am ever feeling nostalgic about the fireplac...      love
6   ive been taking or milligrams or times recomme...  surprise
9                                 i feel romantic too      love
32  i have seen heard and read over the past coupl...  surprise
47  i can t let go of that sad feeling that i want...      love

In [5]:
df1['label'].value_counts()

label
love        1641
surprise     719
Name: count, dtype: int64

We're not getting a lot more instances but anything is better than nothing

## LoSu 2 ([Kaggle link](https://www.kaggle.com/datasets/pashupatigupta/emotion-detection-from-text))

In [6]:
df2 = pd.read_csv("../data/raw/extra_dataset_PashupatiGupta.csv")
df2.head()

     tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...

In [7]:
df2 = df2.drop('tweet_id', axis=1)
df2 = df2.rename(columns={'sentiment': 'label', 'content': 'text'})
df2.head()

        label                                               text
0       empty  @tiffanylue i know  i was listenin to bad habi...
1     sadness  Layin n bed with a headache  ughhhh...waitin o...
2     sadness                Funeral ceremony...gloomy friday...
3  enthusiasm               wants to hang out with friends SOON!
4     neutral  @dannycastillo We want to trade with someone w...

In [8]:
df2 = df2[df2['label'].isin(['love', 'surprise', 'enthusiasm'])]
df2.head()

         label                                               text
3   enthusiasm               wants to hang out with friends SOON!
14    surprise                                       Got the news
16        love                               @annarosekerr agreed
56  enthusiasm  bed...sorta. today was good, sara has strep th...
94        love  @RobertF3 correct! I ADORE him. I just plucked...

In [9]:
df2['label'].value_counts()

label
love          3842
surprise      2187
enthusiasm     759
Name: count, dtype: int64

In [10]:
df2['label'] = df2['label'].replace('enthusiasm', 'surprise')
df2['label'].value_counts()

label
love        3842
surprise    2946
Name: count, dtype: int64

## Merging df1 and df2...

In [11]:
df_merged = pd.concat([df1, df2], ignore_index=True)
df_merged.head()

                                                text     label
0  i am ever feeling nostalgic about the fireplac...      love
1  ive been taking or milligrams or times recomme...  surprise
2                                i feel romantic too      love
3  i have seen heard and read over the past coupl...  surprise
4  i can t let go of that sad feeling that i want...      love

In [12]:
df_merged['label'].value_counts()

label
love        5483
surprise    3665
Name: count, dtype: int64

## LoSu 3 ([Kaggle link](https://www.kaggle.com/datasets/simaanjali/emotion-analysis-based-on-text/data))

In [13]:
df3 = pd.read_csv("../data/raw/extra_dataset_SimaAnjali.csv")
df3.head()

   Unnamed: 0                                               text  Emotion
0           0  i seriously hate one subject to death but now ...     hate
1           1                 im so full of life i feel appalled  neutral
2           2  i sit here to write i start to dig out my feel...  neutral
3           3  ive been really angry with r and i feel like a...    anger
4           4  i feel suspicious if there is no one outside l...  neutral

In [14]:
df3.columns

Index(['Unnamed: 0', 'text', 'Emotion'], dtype='object')

In [15]:
df3 = df3.drop('Unnamed: 0', axis=1)
df3 = df3.rename(columns={'Emotion': 'label'})

In [16]:
df3.head()

                                                text    label
0  i seriously hate one subject to death but now ...     hate
1                 im so full of life i feel appalled  neutral
2  i sit here to write i start to dig out my feel...  neutral
3  ive been really angry with r and i feel like a...    anger
4  i feel suspicious if there is no one outside l...  neutral

In [17]:
df3 = df3[df3['label'].isin(['love', 'surprise'])]
df3.head()

                                                  text label
5    i feel jealous becasue i wanted that kind of l...  love
74   i feel like she has taken on the role of a gra...  love
171  i feel like im back to the arms of a beloved l...  love
356  i am feeling so festive right now and not just...  love
380  i don t discuss even my feelings for beloved w...  love

In [18]:
df3['label'].value_counts()

label
love        39553
surprise     6954
Name: count, dtype: int64

In [19]:
df_merged = pd.concat([df_merged, df3], ignore_index=True)
df_merged.head()

                                                text     label
0  i am ever feeling nostalgic about the fireplac...      love
1  ive been taking or milligrams or times recomme...  surprise
2                                i feel romantic too      love
3  i have seen heard and read over the past coupl...  surprise
4  i can t let go of that sad feeling that i want...      love

In [20]:
df_merged['label'].value_counts()

label
love        45036
surprise    10619
Name: count, dtype: int64

In [21]:
df_merged.drop_duplicates(subset=['text'], inplace=True)
df_merged['label'].value_counts()

label
love        22776
surprise     6974
Name: count, dtype: int64

## LoSu 4 ([Kaggle link](https://www.kaggle.com/datasets/bryanhuerta/social-media-sentiment-data))

In [22]:
df4 = pd.read_csv("../data/raw/extra_dataset_BryanHuerta.csv")
df4.head()

,ID_Column,Text,Sentiment,Time_Column,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,17,Late-night gaming session with friends.,Positive,2023-01-20 00:05:00.000000 UTC,GamerX,Twitter,#Gaming #LateNight,18,35,UK,2023,1,20,0
1,327,"Fearful eyes scanning the shadows, a prisoner...",Fearful,2023-01-07 03:30:00.000000 UTC,NightPrisoner,Twitter,#Fearful #LurkingMonsters,18,36,India,2023,1,7,3
2,336,"Loneliness, a silent companion in the night, ...",Loneliness,2019-09-19 03:30:00.000000 UTC,NocturnalEcho,Facebook,#Loneliness #SolitaryNocturne,18,36,Australia,2019,9,19,3
3,305,"Eyes wide open in the night, fearful shadows ...",Fearful,2022-05-12 02:00:00.000000 UTC,NightPrisoner,Facebook,#Fearful #ImaginedHorrors,18,36,India,2022,5,12,2
4,510,"At the summit of Mount Fuji, a breathtaking su...",Accomplishment,2020-04-15 05:30:00.000000 UTC,FujiSummitAchiever,Facebook,#Accomplishment #SunriseHues,28,55,Japan,2020,4,15,5

In [23]:
df4 = df4[['Text', 'Sentiment']]
df4 = df4.rename(columns={'Text': 'text', 'Sentiment': 'label'})

In [24]:
unique_labels = df4['label'].unique()
print(', '.join(unique_labels))

Positive, Fearful, Loneliness, Accomplishment, Hopeful, Awe, Anticipation, Motivation, Despair, Negative, Gratitude, Empowerment, Love, Overwhelmed, Curiosity, Proud, InnerJourney, Mindfulness, Disgust, Confusion, Anxiety, Frustrated, Calmness, Neutral, Disappointed, Blessed, Anger, Arousal, Contentment, Grateful, Optimism, LostLove, Elation, Ambivalence, Apprehensive, Bitterness, Determination, Jealous, Excitement, Regret, Compassionate, Free-spirited, Adoration, Acceptance, Radiance, Betrayal, Happiness, Envy, Jealousy, Euphoria, Kind, Admiration, Ruins, Heartbreak, Satisfaction, Devastated, Inspiration, Resentment, Amusement, Shame, Surprise, Bad, Hate, Joy, Thrill, Adrenaline, Happy, Kindness, Desolation, Enthusiasm, Exploration, Relief, Confident, Appreciation, Freedom, Amazement, DreamChaser, Exhaustion, Helplessness, Numbness, Dismissive, Frustration, Pride, Nostalgia, Empathetic, Rejuvenation, Compassion, Inspired, Sad, Whimsy, Grief, Adventure, Desperation, Serenity, Sadness, Loss, Mischievous, Resilience, Isolation, Bitter, Reverence, Marvel, FestiveJoy, PlayfulJoy, Playful, Enchantment, Indifference, Yearning, Affection, ArtisticBurst, Creativity, Zest, Hope, Romance, Embarrassed, Tranquility, Breakthrough, Wonder, Friendship, Confidence, Pensive, Intrigue, Reflection, Melodic, JoyfulReunion, Joy in Baking, Captivation, EmotionalStorm, Winter Magic, Intimidation, Pressure, Disappointment, Bittersweet, Charm, Ocean's Freedom, Grandeur, Fulfillment, Sorrow, Nature's Beauty, Darkness, Touched, Envisioning History, Coziness, Journey, Solace, Wonderment, Boredom, Melancholy, Positivity, Overjoyed, Harmony, Envious, Immersion, Renewed Effort, Creative Inspiration, Tenderness, Enjoyment, Connection, Suffering, Engagement, Emotion, Culinary Adventure, Celestial Wonder, Heartwarming, Miscalculation, Elegance, Dazzle, Sympathy, Whispers of the Past, CulinaryOdyssey, Imagination, Fear, Triumph, Thrilling Journey, Vibrancy, Celebration, Runway Creativity, Hypnotic, Contemplation, Challenge, Energy, Obstacle, Iconic, Colorful, Success, Heartache, Solitude, Ecstasy, Suspense, Mesmerizing, Spark

Awe, Gratitude, Love, Confusion, Arousal, Adoration, Admiration, Thrill, Adrenaline, Wonder, Energy, Suspense

In [25]:
labels_to_keep = ['Awe', 'Gratitude', 'Love', 'Confusion', 'Arousal', 'Adoration', 'Admiration', 'Thrill', 'Adrenaline', 'Wonder', 'Energy', 'Suspense']
df4_copy = df4[df4['label'].isin(labels_to_keep)].copy()
df4_copy['label'].value_counts()

label
Gratitude     17
Awe            9
Confusion      8
Arousal        4
Thrill         4
Admiration     4
Love           3
Wonder         3
Adoration      2
Adrenaline     1
Energy         1
Suspense       1
Name: count, dtype: int64

In [26]:
labels_to_display = ['Wonder', 'Adrenaline', 'Arousal', 'Thrill', 'Suspense']
filtered_df = df4_copy[df4_copy['label'].isin(labels_to_display)]
for index, row in filtered_df.iterrows():
    print(f"{row['text']}, {row['label']}")

Arousal of excitement before a much-awaited trip., Arousal
Arousal of excitement as I await a special announcement., Arousal
Arousal of excitement for an upcoming adventure., Arousal
Arousal of excitement for an upcoming festival., Arousal
Embracing the thrill of speed on a rollercoaster's exhilarating twists., Thrill
Riding the adrenaline rush on a rollercoaster's wild twists., Adrenaline
Thrilled to witness the grandeur of a cultural festival., Thrill
In the carnival of emotions, the rollercoaster of thrill sends the heart on a wild ride. , Thrill
In the midst of the Amazon rainforest, a symphony of wildlife creates an orchestra of nature's wonders. , Wonder
Experiencing the thrill of a high-speed Formula 1 race, fans are on the edge of their seats as drivers compete for the championship. , Thrill
Binge-watching a thrilling crime series, the suspense keeps the viewer on the edge of their seat, creating a rush of adrenaline. , Suspense
Awe-inspired by the vastness of the cosmos on a stargazing night., Wonder
A sense of wonder at the vastness of the cosmos on a stargazing night., Wonder

In [27]:
filtered_df = df4_copy[df4_copy['label'].isin(['Awe'])]
for index, row in filtered_df.iterrows():
    print(f"{row['text']}, {row['label']}")

Awe-struck by the breathtaking sunrise over the mountains., Awe
Awe-struck by the grandeur of an ancient cathedral's intricate architecture., Awe
Awe-inspired by the grandeur of an ancient cathedral's intricate architecture., Awe
In the embrace of the Grand Canyon, nature's masterpiece, a moment to marvel at Earth's grandeur. , Awe
At the golf tournament, the golfer's precision and focus lead to a stunning victory, leaving spectators in awe of their exceptional skill. , Awe
Walking the Great Wall of China, each step a testament to ancient engineering marvels. , Awe
Experiencing awe at the breathtaking sunset., Awe
Awe-struck by the beauty of the night sky., Awe
At the summit of Machu Picchu, a breathtaking panorama that whispers the secrets of ancient civilizations. , Awe

In [28]:
labels_to_surprise = ['Surprise', 'Awe', 'Confusion', 'Arousal', 'Thrill', 'Adrenaline', 'Wonder', 'Energy', 'Suspense']
labels_to_love = ['Gratitude', 'Love', 'Adoration', 'Admiration']

In [29]:
df4_copy['label'] = df4_copy['label'].replace(labels_to_surprise, 'surprise')
df4_copy['label'] = df4_copy['label'].replace(labels_to_love, 'love')
df4_copy['label'].value_counts()

label
surprise    31
love        26
Name: count, dtype: int64

In [30]:
df_merged = pd.concat([df_merged, df4_copy], ignore_index=True)
df_merged['label'].value_counts()

label
love        22802
surprise     7005
Name: count, dtype: int64

## Custom dataset for surprise (Surprise synth)

In [31]:
# Load more_surprise.csv
df_surprise = pd.read_csv("../data/raw/more_surprise.csv")
df_surprise.head()

                                                text     label
0  ﻿I froze as the door swung open to reveal ever...  surprise
1  My jaw dropped when the email announced the gr...  surprise
2      I can't tell the difference between these two  surprise
3                    Nobody knows what they're doing  surprise
4  When someone says something for the third time...  surprise

Yay we have 663 more instances for `surprise`

Let's merge everything now and save it:

## Merge love and surprise datasets

In [32]:
df_merged = pd.concat([df_merged, df_surprise], ignore_index=True)
df_merged['label'].value_counts()

label
love        22802
surprise     7668
Name: count, dtype: int64

In [51]:
df_merged.shape[0]

30470

In [52]:
df_merged.drop_duplicates(subset=['text'], inplace=True)
df_merged.shape[0]

30470

In [53]:
df_merged.to_csv('../data/raw/love_surprise_bonus.csv', index=False)
print("CSV file created successfully!")

CSV file created successfully!

# **Disgust**

In [54]:
path_kaggle1_disgust = "../data/raw/muhammadummarattique_data/disgust"
path_kaggle2_disgust = "../data/raw/emotions_description_RadeDacevic.xlsx"

path_semeval_dev = "../data/raw/semeval/2018-E-c-En-dev.txt"
path_semeval_test = "../data/raw/semeval/2018-E-c-En-test.txt"
path_semeval_train = "../data/raw/semeval/2018-E-c-En-train.txt"

path_disgust = "../data/raw/disgust_original.csv"

## Disgust 1 ([Kaggle link](https://www.kaggle.com/datasets/muhammadumarattique/text-for-emotions-classification-projests))

In [55]:
disgust_texts = []

for filename in os.listdir(path_kaggle1_disgust):
    if filename.endswith('.txt'):
        filepath = os.path.join(path_kaggle1_disgust, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            disgust_texts.append({'text': content, 'label': 'disgust'})

df1_d = pd.DataFrame(disgust_texts)
df1_d.head()

                                                text    label
0  The nauseating stench of rotting meat mingled ...  disgust
1  Another repulsive scene unfolded as a mix of d...  disgust
2  The sight of moldy food combined with the foul...  disgust
3  The putrid stench of rotting meat made me gag ...  disgust
4  A slimy, moldy substance oozed from the trash ...  disgust

In [56]:
df1_d.shape

(1722, 2)

## ISEAR ([Hugging Face](https://huggingface.co/datasets/gsri-18/ISEAR-dataset-complete))

In [57]:
import pandas as pd

df2_d = pd.read_csv("hf://datasets/gsri-18/ISEAR-dataset-complete/ISEAR_dataset_complete.csv")

In [58]:
df2_d.head()

   emotion                                            content Unnamed: 2
0      joy  On days when I feel close to my partner and ot...        NaN
1     fear  Every time I imagine that someone I love or I ...        NaN
2    anger  When I had been obviously unjustly treated and...        NaN
3  sadness  When I think about the short time that we live...        NaN
4  disgust  At a gathering I found myself involuntarily si...        NaN

In [59]:
df2_d['emotion'].value_counts()

emotion
joy        1092
sadness    1082
anger      1079
fear       1076
shame      1071
disgust    1066
guilt      1050
Name: count, dtype: int64

In [60]:
df2_d = df2_d[df2_d['emotion']=='disgust']
df2_d.shape

(1066, 3)

In [61]:
# Rename column emotion to label and content to text
df2_d = df2_d.rename(columns={'emotion': 'label', 'content': 'text'})
df2_d.drop('Unnamed: 2', axis=1, inplace=True)
df2_d.head()

      label                                               text
4   disgust  At a gathering I found myself involuntarily si...
11  disgust    When I found a bristle in the liver paste tube.
18  disgust  When one finds out that someone you know is no...
28  disgust  When I nearly walked on a blindworm and then s...
35  disgust  A drunkard fell, started bleeding and wet hims...

## Semeval-2018 Task E-c ([Github link](https://github.com/cbaziotis/ntua-slp-semeval2018/tree/master/datasets/task1/E-c))

In [62]:
import pandas as pd

base_raw_url = "https://raw.githubusercontent.com/cbaziotis/ntua-slp-semeval2018/master/datasets/task1/E-c/"

files = {
    "train": "E-c-En-train.txt",
    "dev": "E-c-En-dev.txt",
    "test": "E-c-En-test-gold.txt"
}

dataframes = []
for split, filename in files.items():
    url = base_raw_url + filename
    df = pd.read_csv(url, sep='\t', header=0, encoding='utf-8')
    df['split'] = split
    dataframes.append(df)

df3_d = pd.concat(dataframes, ignore_index=True)
df3_d.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust,split
0,2017-En-21441,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1,train
1,2017-En-31535,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0,train
2,2017-En-21068,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0,train
3,2017-En-31436,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0,train
4,2017-En-22195,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0,train

In [63]:
df3_d.dtypes

ID              object
Tweet           object
anger            int64
anticipation     int64
disgust          int64
fear             int64
joy              int64
love             int64
optimism         int64
pessimism        int64
sadness          int64
surprise         int64
trust            int64
split           object
dtype: object

In [64]:
df3_d = df3_d.rename(columns={"Tweet": "text"})
df3_d = df3_d[df3_d["disgust"]==1]
df3_d.shape

(4020, 14)

In [65]:
df3_d = df3_d[df3_d["disgust"].astype(str).eq("1")].copy()
df3_d["label"] = "disgust"
df3_d = df3_d[["text", "label"]]
df3_d.drop_duplicates(subset=['text'], inplace=True)
df3_d.shape

(4020, 2)

## Merge disgust datasets

In [66]:
df_merged_d = pd.concat([df1_d, df2_d, df3_d], ignore_index=True)
df_merged_d.head()

                                                text    label
0  The nauseating stench of rotting meat mingled ...  disgust
1  Another repulsive scene unfolded as a mix of d...  disgust
2  The sight of moldy food combined with the foul...  disgust
3  The putrid stench of rotting meat made me gag ...  disgust
4  A slimy, moldy substance oozed from the trash ...  disgust

In [67]:
df_merged_d.shape[0]

6808

In [68]:
df_merged_d.drop_duplicates(subset=['text'], inplace=True)
df_merged_d.shape[0]

6719

In [71]:
df_merged_d.to_csv(path_disgust, index=False)
print("Saved merged disgust dataset -> ", path_disgust)

Saved merged disgust dataset ->  ../data/raw/disgust_original.csv